name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.0
homepage: https://github.com/iqonicdesignofficial/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  mockito: ^5.4.4


flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass:  FlutterPaystackPlugin
      ios:
        pluginClass:  FlutterPaystackPlugin

  assets:
   - assets/images/



environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"
